### ISSUE TITLE
Is there a way to output the pgn-file?

### ISSUE THREAD

**Issue by JSDurand** [jwiegley/emacs-chess#10]
I am new to emacs, and to emacs-chess.
After some try I finally managed to play with the computer, but after the match, if I want to store the game as a pgn-file, how should I do it?
I have looked at the available commands after `M-x chess` but found no obvious options.
Sorry for this simple question. And thanks for any help. :)

**Comment by tychobrailleur** [comment]
You can copy the current game as PGN with `C-u M-w` – you can then yank it into any buffer with `C-y`.

**Comment by jwiegley** [comment]
There should be a "Save current PGN to file" command.

**Comment by WorldsEndless** [comment]
I can't find said command, but the key chord above works.

**Comment by JSDurand** [comment]
Thanks! Somehow I missed that comment for two years!

**Comment by touxstone** [comment]
> You can copy the current game as PGN with `C-u M-w` – you can then yank it into any buffer with `C-y`.

Yeap. It works. Thanks! I can save the current (e.g. an unfinished) game now, but I'm unable to carry on it once loaded it later (I only could go back/forward step by step over the game saved using the `<` and `>` keyboard keys). How-to I could make it live again?

**Comment by WorldsEndless** [comment]
I've been having the same problem
