### ISSUE TITLE
default directory for puzzles

### ISSUE THREAD

**Issue by dwcoates** [jwiegley/emacs-chess#13]
It would be nice for there to be a default directory for puzzles. It's a real chore to navigate to my puzzle directory whenever I'd like to solve a random tactic from my puzzle directory. This is an unacceptable interference with my ability to procrastinate. If you agree, I can implement this and file a pull request.

**Comment by jwiegley** [comment]
Sounds like a great idea. We can't have too much productivity.

http://2.bp.blogspot.com/-Itw_OLDmScQ/Upvh0zdThcI/AAAAAAAAGbc/oTJBvQsSgaA/s1600/IGM+RDM+interacting+1.png
